### ISSUE TITLE
Issue #5

### ISSUE THREAD

**Issue by WilliamsPJ19** [PRiSMA-Study/Monitoring-Report#5]
https://github.com/PRiSMA-Study/Monitoring-Report-ACTIVE/blob/d0bc16f8407dee91433318ef1d67a5a7d5c9a7bf/4.%20Report_Setup-Active.R#L711C40-L711C49

ANC20 END PREG should  be greater than 181days

**Comment by sloisate2** [comment]
Great catch! I have updated. Thank you, Precious
